# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00870c5ba4ba2f1069153a22fb1d5e813d324eb6de4f5504749491517243b917c9746c541a1f13e8645d06eed1c67777c1224a50ad5fcdb6ec0abe53dd8cba3

test:
  secret_key_base: 8350e405a1204ac02eba85ee9ddc959caf3ea0f760a29e5e32c62798927321b8b89be078f8e4f81fbecc01d9a18917c8866cf15b1d0caae4b439f12ace91c907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
